version: "3.1"
services:
  mongo:
    container_name: mongo-meurestaurante
    image: mongo:latest
    restart: always
    ports:
      - 27015:27015
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - meurestaurante-api

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3031:3030
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - meurestaurante-api

networks:
  meurestaurante-api:
    external: false
